services:
    run:
        container_name: flask-dash
        image: darlon/flask-dash
        # environment:
            # - STREAMLIT_SERVER_ADDRESS=0.0.0.0
            # - STREAMLIT_BROWSER_SERVER_PORT=8501
        volumes:
            - ./:/data
        # ports:
            # - "8501:8501" #Streamlit
        working_dir: /data
        # command: /usr/local/bin/streamlit run --browser.serverAddress 0.0.0.0 --browser.serverPort 8501 ./interface_st.py 
        # command: /usr/local/bin/streamlit run ./interface_st.py 
        # restart: always